import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const packages = [
  {
    durationDays: 30,
    isActive: true,
    maxDevices: 1,
    name: "Individual",
    price: 49000,
    quality: "720p",
  },
  {
    durationDays: 30,
    isActive: true,
    maxDevices: 2,
    name: "Berdua",
    price: 79000,
    quality: "1080p",
  },
  {
    durationDays: 30,
    isActive: true,
    maxDevices: 7,
    name: "Keluarga",
    price: 159000,
    quality: "4K",
  },
];

const genres = [
  ["Aksi", "aksi"],
  ["Anak-anak", "anak-anak"],
  ["Anime", "anime"],
  ["Britania", "britania"],
  ["Drama", "drama"],
  ["Fantasi Ilmiah & Fantasi", "fantasi-ilmiah-fantasi"],
  ["Kejahatan", "kejahatan"],
  ["KDrama", "kdrama"],
  ["Komedi", "komedi"],
  ["Petualangan", "petualangan"],
  ["Perang", "perang"],
  ["Romantis", "romantis"],
  ["Sains & Alam", "sains-alam"],
  ["Thriller", "thriller"],
];

const imageUrl = (path, size = "w342") =>
  path.startsWith("http") ? path : `https://image.tmdb.org/t/p/${size}/${path}`;

const episode = (title, duration, episodeNumber = null, description = null) => ({
  description:
    description ??
    `${title} membawa cerita utama bergerak maju dengan konflik baru.`,
  duration,
  episodeNumber,
  seasonNumber: episodeNumber ? 1 : null,
  thumbnailUrl: null,
  title,
  videoUrl: null,
});

const movieEpisode = (title, duration) =>
  episode(title, duration, null, `${title} tersedia sebagai trailer demo.`);

const contents = [
  {
    ageRating: "13+",
    badge: "Premium",
    description:
      "Jake Sully dan keluarganya menjelajahi wilayah Pandora yang baru saat ancaman lama kembali mengejar mereka.",
    episodes: [movieEpisode("Avatar: The Way of Water", "3j 12m")],
    genreSlugs: ["aksi", "petualangan", "fantasi-ilmiah-fantasi"],
    image: imageUrl("t6HIqrRAclMCA60NsSmeqe9RmNV.jpg"),
    isPremium: true,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg", "w780"),
    publishedAt: new Date("2026-01-02"),
    rating: 4.7,
    releaseYear: 2022,
    slug: "avatar-the-way-of-water",
    title: "Avatar: The Way of Water",
    trailerUrl: "https://www.youtube.com/embed/d9MyW72ELq0",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Para Guardians menjalankan misi berbahaya untuk menyelamatkan Rocket dan menjaga keluarga mereka tetap utuh.",
    episodes: [movieEpisode("Guardians of the Galaxy Vol. 3", "2j 30m")],
    genreSlugs: ["aksi", "komedi", "petualangan"],
    image: imageUrl("r2J02Z2OpNTctfOSN1Ydgii51I3.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg", "w780"),
    publishedAt: new Date("2026-01-03"),
    rating: 4.8,
    releaseYear: 2023,
    slug: "guardians-of-the-galaxy-vol-3",
    title: "Guardians of the Galaxy Vol. 3",
    trailerUrl: "https://www.youtube.com/embed/u3V5KDHRQvk",
    type: "MOVIE",
  },
  {
    ageRating: "16+",
    badge: null,
    description:
      "Batman menyelidiki teka-teki kelam yang menghubungkan kriminal Gotham dengan masa lalu keluarganya.",
    episodes: [movieEpisode("The Batman", "2j 56m")],
    genreSlugs: ["aksi", "kejahatan", "thriller"],
    image: imageUrl("74xTEgt7R36Fpooo50r9T25onhq.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("rvtdN5XkWAfGX6xDuPL6yYS2seK.jpg", "w780"),
    publishedAt: new Date("2026-01-04"),
    rating: 4.5,
    releaseYear: 2022,
    slug: "the-batman",
    title: "The Batman",
    trailerUrl: "https://www.youtube.com/embed/mqqft2x_Aa4",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Dua astronom memperingatkan dunia tentang komet besar, tetapi respons publik berubah menjadi kekacauan media.",
    episodes: [movieEpisode("Don't Look Up", "2j 18m")],
    genreSlugs: ["drama", "komedi", "sains-alam"],
    image: imageUrl("nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg", "w780"),
    publishedAt: new Date("2026-01-05"),
    rating: 4.5,
    releaseYear: 2021,
    slug: "dont-look-up",
    title: "Don't Look Up",
    trailerUrl: "https://www.youtube.com/embed/RbIxYm3mKzI",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Seorang duda pemarah mulai menemukan kembali makna hidup setelah keluarga baru pindah ke lingkungannya.",
    episodes: [movieEpisode("A Man Called Otto", "2j 6m")],
    genreSlugs: ["drama", "komedi", "romantis"],
    image: imageUrl("9ZznETDyfPWVugRiv0jfGrkRftw.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("9ZznETDyfPWVugRiv0jfGrkRftw.jpg", "w780"),
    publishedAt: new Date("2026-01-06"),
    rating: 4.4,
    releaseYear: 2022,
    slug: "a-man-called-otto",
    title: "A Man Called Otto",
    trailerUrl: "https://www.youtube.com/embed/eFYUX9l-m5I",
    type: "MOVIE",
  },
  {
    ageRating: "7+",
    badge: "Episode Baru",
    description:
      "Sonic dan Tails bekerja sama menghentikan ancaman baru yang memburu kekuatan zamrud legendaris.",
    episodes: [movieEpisode("Sonic the Hedgehog 2", "2j 2m")],
    genreSlugs: ["anak-anak", "komedi", "petualangan"],
    image: imageUrl("6DrHO1jr3qVrViUO6s6kFiAGM7.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("egoyMDLqCxzjnSrWOz50uLlJWmD.jpg", "w780"),
    publishedAt: new Date("2026-01-07"),
    rating: 4.5,
    releaseYear: 2022,
    slug: "sonic-the-hedgehog-2",
    title: "Sonic the Hedgehog 2",
    trailerUrl: "https://www.youtube.com/embed/G5kzUpWAusI",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Sekelompok penjelajah melintasi ruang dan waktu untuk mencari harapan baru bagi umat manusia.",
    episodes: [movieEpisode("Interstellar", "2j 49m")],
    genreSlugs: ["drama", "petualangan", "sains-alam"],
    image: imageUrl("gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("xJHokMbljvjADYdit5fK5VQsXEG.jpg", "w780"),
    publishedAt: new Date("2026-01-08"),
    rating: 4.9,
    releaseYear: 2014,
    slug: "interstellar",
    title: "Interstellar",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Seorang pencuri memasuki alam mimpi untuk menanamkan ide dalam target yang sangat dilindungi.",
    episodes: [movieEpisode("Inception", "2j 28m")],
    genreSlugs: ["aksi", "sains-alam", "thriller"],
    image: imageUrl("edv5CZvWj09upOsy2Y6IwDhK8bt.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("s3TBrRGB1iav7gFOCNx3H31MoES.jpg", "w780"),
    publishedAt: new Date("2026-01-09"),
    rating: 4.8,
    releaseYear: 2010,
    slug: "inception",
    title: "Inception",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    type: "MOVIE",
  },
  {
    ageRating: "16+",
    badge: null,
    description:
      "Kisah ilmuwan J. Robert Oppenheimer dan proyek rahasia yang mengubah sejarah dunia.",
    episodes: [movieEpisode("Oppenheimer", "3j")],
    genreSlugs: ["drama", "perang"],
    image: imageUrl("8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
    isPremium: true,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg", "w780"),
    publishedAt: new Date("2026-01-10"),
    rating: 4.8,
    releaseYear: 2023,
    slug: "oppenheimer",
    title: "Oppenheimer",
    trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Barbie meninggalkan dunianya yang sempurna dan menemukan pertanyaan baru tentang hidup nyata.",
    episodes: [movieEpisode("Barbie", "1j 54m")],
    genreSlugs: ["komedi", "petualangan", "fantasi-ilmiah-fantasi"],
    image: imageUrl("iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("nHf61UzkfFno5X1ofIhugCPus2R.jpg", "w780"),
    publishedAt: new Date("2026-01-11"),
    rating: 4.3,
    releaseYear: 2023,
    slug: "barbie",
    title: "Barbie",
    trailerUrl: "https://www.youtube.com/embed/pBk4NYhWNMM",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: "Episode Baru",
    description:
      "Seorang gadis membuka pintu misterius yang menghubungkan bencana di berbagai wilayah Jepang.",
    episodes: [movieEpisode("Suzume", "2j 2m")],
    genreSlugs: ["anime", "drama", "fantasi-ilmiah-fantasi"],
    image: imageUrl("vIeu8WysZrTSFb2uhPViKjX9EcC.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("vIeu8WysZrTSFb2uhPViKjX9EcC.jpg", "w780"),
    publishedAt: new Date("2026-01-12"),
    rating: 4.6,
    releaseYear: 2022,
    slug: "suzume",
    title: "Suzume",
    trailerUrl: "https://www.youtube.com/embed/5pTcio2hTSw",
    type: "MOVIE",
  },
  {
    ageRating: "7+",
    badge: "Premium",
    description:
      "Hiro dan robot perawat Baymax membentuk tim pahlawan untuk menghadapi ancaman teknologi.",
    episodes: [movieEpisode("Big Hero 6", "1j 42m")],
    genreSlugs: ["anak-anak", "aksi", "komedi"],
    image: imageUrl("2mxS4wUimwlLmI1xp6QW6NSU361.jpg"),
    isPremium: true,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("2mxS4wUimwlLmI1xp6QW6NSU361.jpg", "w780"),
    publishedAt: new Date("2026-01-13"),
    rating: 4.5,
    releaseYear: 2014,
    slug: "big-hero-6",
    title: "Big Hero 6",
    trailerUrl: "https://www.youtube.com/embed/z3biFxZIJOQ",
    type: "MOVIE",
  },
  {
    ageRating: "16+",
    badge: "Top 10",
    description:
      "Prajurit dari masa depan datang membawa peringatan perang besar melawan makhluk asing.",
    episodes: [movieEpisode("The Tomorrow War", "2j 20m")],
    genreSlugs: ["aksi", "perang", "sains-alam"],
    image: imageUrl("34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg", "w780"),
    publishedAt: new Date("2026-01-14"),
    rating: 4.3,
    releaseYear: 2021,
    slug: "the-tomorrow-war",
    title: "The Tomorrow War",
    trailerUrl: "https://www.youtube.com/embed/RQjEbkV-9ZM",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: "Top 10",
    description:
      "Scott Lang dan keluarganya terseret ke dunia Quantum dan bertemu ancaman besar bernama Kang.",
    episodes: [movieEpisode("Ant-Man and the Wasp: Quantumania", "2j 5m")],
    genreSlugs: ["aksi", "petualangan", "fantasi-ilmiah-fantasi"],
    image: imageUrl("ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("m8JTwHFwX7I7JY5fPe4SjqejWag.jpg", "w780"),
    publishedAt: new Date("2026-01-15"),
    rating: 4.1,
    releaseYear: 2023,
    slug: "ant-man-and-the-wasp-quantumania",
    title: "Ant-Man and the Wasp: Quantumania",
    trailerUrl: "https://www.youtube.com/embed/ZlNFpri-Y40",
    type: "MOVIE",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Seorang anak mencari ibunya lewat jejak digital dan menemukan rahasia yang berlapis.",
    episodes: [movieEpisode("Missing", "1j 51m")],
    genreSlugs: ["drama", "kejahatan", "thriller"],
    image: imageUrl("wEOUYSU5Uf8J7152PT6jdb5233Y.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("gxRKsjkFJLgJtpEAf9ttnciJfg0.jpg", "w780"),
    publishedAt: new Date("2026-01-16"),
    rating: 4.2,
    releaseYear: 2023,
    slug: "missing",
    title: "Missing",
    trailerUrl: "https://www.youtube.com/embed/seBixtcx19E",
    type: "MOVIE",
  },
  {
    ageRating: "16+",
    badge: "Episode Baru",
    description:
      "Sekolah menjadi pusat wabah zombie dan para siswa harus bertahan hidup tanpa bantuan orang dewasa.",
    episodes: [
      episode("Episode 1", "1j 6m", 1),
      episode("Episode 2", "1j 10m", 2),
      episode("Episode 3", "1j 2m", 3),
      episode("Episode 4", "1j 12m", 4),
      episode("Episode 5", "1j 8m", 5),
    ],
    genreSlugs: ["drama", "kejahatan", "thriller"],
    image: imageUrl("pTEFqAjLd5YTsMD6NSUxV6Dq7A6.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl(
      "https://images.saymedia-content.com/.image/t_share/MTg3Nzc5OTg0OTAzMDU0Njgx/tv-review-all-of-us-are-dead.jpg",
    ),
    publishedAt: new Date("2026-02-01"),
    rating: 4.5,
    releaseYear: 2022,
    slug: "all-of-us-are-dead",
    title: "All of Us Are Dead",
    trailerUrl: "https://www.youtube.com/embed/IN5TD4VRcSM",
    type: "SERIES",
  },
  {
    ageRating: "16+",
    badge: "Episode Baru",
    description:
      "Pelatih sepak bola Amerika pindah ke Inggris untuk melatih klub sepak bola profesional.",
    episodes: [
      episode("Pilot", "30 min", 1),
      episode("Biscuits", "29 min", 2),
      episode("Trent Crimm: Independent", "30 min", 3),
      episode("For The Children", "33 min", 4),
      episode("Tan Lines", "31 min", 5),
    ],
    genreSlugs: ["komedi", "drama", "britania"],
    image: imageUrl("5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg", "w780"),
    publishedAt: new Date("2026-02-02"),
    rating: 4.8,
    releaseYear: 2020,
    slug: "ted-lasso",
    title: "Ted Lasso",
    trailerUrl: "https://www.youtube.com/embed/3u7EIiohs6U",
    type: "SERIES",
  },
  {
    ageRating: "16+",
    badge: "Episode Baru",
    description:
      "Para peserta masuk ke Tokyo kosong dan dipaksa bermain game mematikan untuk bertahan hidup.",
    episodes: [
      episode("Episode 1", "49 min", 1),
      episode("Episode 2", "50 min", 2),
      episode("Episode 3", "43 min", 3),
      episode("Episode 4", "52 min", 4),
      episode("Episode 5", "45 min", 5),
    ],
    genreSlugs: ["thriller", "drama", "fantasi-ilmiah-fantasi"],
    image: imageUrl("Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("QZaPkNUvhdcKONuO2fXuqtcQRo.jpg", "w780"),
    publishedAt: new Date("2026-02-03"),
    rating: 4.6,
    releaseYear: 2020,
    slug: "alice-in-borderland",
    title: "Alice in Borderland",
    trailerUrl: "https://www.youtube.com/embed/49_44FFKZ1M",
    type: "SERIES",
  },
  {
    ageRating: "16+",
    badge: "Episode Baru",
    description:
      "Siswa sekolah direkrut menjadi pasukan cadangan saat benda asing mengancam bumi.",
    episodes: [
      episode("The First Mission", "1j 3m", 1),
      episode("After School", "1j 5m", 2),
      episode("Live Fire", "1j 1m", 3),
      episode("Broken Line", "1j 2m", 4),
      episode("Last Bell", "1j 4m", 5),
    ],
    genreSlugs: ["aksi", "drama", "sains-alam"],
    image: imageUrl("5kMIZHO8OYOC08urACEFFqmFA4p.jpg"),
    isPremium: true,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("5kMIZHO8OYOC08urACEFFqmFA4p.jpg", "w780"),
    publishedAt: new Date("2026-02-04"),
    rating: 4.4,
    releaseYear: 2023,
    slug: "duty-after-school",
    title: "Duty After School",
    trailerUrl: "https://www.youtube.com/embed/9y1HbNnT8DI",
    type: "SERIES",
  },
  {
    ageRating: "13+",
    badge: "Episode Baru",
    description:
      "Para striker muda mengikuti program ekstrem untuk menjadi penyerang terbaik di Jepang.",
    episodes: [
      episode("Dream", "24 min", 1),
      episode("Monster", "24 min", 2),
      episode("Soccer Zero", "24 min", 3),
      episode("Premonition", "24 min", 4),
      episode("To Be Reborn", "24 min", 5),
    ],
    genreSlugs: ["anime", "drama", "aksi"],
    image: imageUrl("seMRyWVwIVBWbC9xaMzDMZJ8fUH.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("seMRyWVwIVBWbC9xaMzDMZJ8fUH.jpg", "w780"),
    publishedAt: new Date("2026-02-05"),
    rating: 4.6,
    releaseYear: 2022,
    slug: "blue-lock",
    title: "Blue Lock",
    trailerUrl: "https://www.youtube.com/embed/IVsII3dLbWc",
    type: "SERIES",
  },
  {
    ageRating: "16+",
    badge: "Episode Baru",
    description:
      "Manusia bertahan dari serangan Titan raksasa sambil mengungkap rahasia tembok yang melindungi mereka.",
    episodes: [
      episode("To You, in 2000 Years", "24 min", 1),
      episode("That Day", "24 min", 2),
      episode("A Dim Light", "24 min", 3),
      episode("Night of the Closing Ceremony", "24 min", 4),
      episode("First Battle", "24 min", 5),
    ],
    genreSlugs: ["anime", "aksi", "drama"],
    image: imageUrl("hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: false,
    previewImage: imageUrl("hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg", "w780"),
    publishedAt: new Date("2026-02-06"),
    rating: 4.9,
    releaseYear: 2013,
    slug: "attack-on-titan",
    title: "Attack on Titan",
    trailerUrl: "https://www.youtube.com/embed/LV-nazLVmgo",
    type: "SERIES",
  },
  {
    ageRating: "16+",
    badge: "Premium",
    description:
      "Wabah misterius mengunci penghuni apartemen dan membuat batas antara manusia dan monster makin tipis.",
    episodes: [
      episode("Public Rental Apartment", "1j 5m", 1),
      episode("Thirsty Patients", "1j 4m", 2),
      episode("Locked In", "1j 2m", 3),
      episode("The Contract", "1j 1m", 4),
      episode("The New Normal", "1j 3m", 5),
    ],
    genreSlugs: ["kdrama", "thriller", "drama"],
    image: imageUrl("8lBlBItnehgOAwFt0ezxlXuWeIO.jpg"),
    isPremium: true,
    isTopTen: false,
    isTrending: true,
    previewImage: imageUrl("8lBlBItnehgOAwFt0ezxlXuWeIO.jpg", "w780"),
    publishedAt: new Date("2026-02-07"),
    rating: 4.5,
    releaseYear: 2021,
    slug: "happiness",
    title: "Happiness",
    trailerUrl: "https://www.youtube.com/embed/gqhUlldiLEk",
    type: "SERIES",
  },
  {
    ageRating: "13+",
    badge: null,
    description:
      "Seorang reporter dan pria dari masa lalu menyelidiki pembunuhan yang mengubah waktu.",
    episodes: [
      episode("Unexpected Encounter", "1j 2m", 1),
      episode("The Time Door", "1j 1m", 2),
      episode("A Strange Village", "1j 3m", 3),
      episode("The Evidence", "1j", 4),
      episode("The Suspect", "1j 4m", 5),
    ],
    genreSlugs: ["kdrama", "drama", "fantasi-ilmiah-fantasi"],
    image: imageUrl("7zM8X0XcJLUqYgxwJZtUY2WwhxP.jpg"),
    isPremium: false,
    isTopTen: false,
    isTrending: false,
    previewImage: imageUrl("7zM8X0XcJLUqYgxwJZtUY2WwhxP.jpg", "w780"),
    publishedAt: new Date("2026-02-08"),
    rating: 4.3,
    releaseYear: 2023,
    slug: "my-perfect-stranger",
    title: "My Perfect Stranger",
    trailerUrl: "https://www.youtube.com/embed/Z7fAkqHMpLQ",
    type: "SERIES",
  },
  {
    ageRating: "7+",
    badge: "Premium",
    description:
      "Baymax berkeliling kota untuk membantu orang-orang dengan perhatian kecil yang hangat.",
    episodes: [
      episode("Cass", "12 min", 1),
      episode("Kiko", "12 min", 2),
      episode("Sofia", "12 min", 3),
      episode("Mbita", "12 min", 4),
      episode("Yachi", "12 min", 5),
    ],
    genreSlugs: ["anak-anak", "komedi", "petualangan"],
    image: imageUrl("rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg"),
    isPremium: true,
    isTopTen: false,
    isTrending: false,
    previewImage: imageUrl("rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg", "w780"),
    publishedAt: new Date("2026-02-09"),
    rating: 4.2,
    releaseYear: 2022,
    slug: "baymax",
    title: "Baymax!",
    trailerUrl: "https://www.youtube.com/embed/6d6e7h6WqvE",
    type: "SERIES",
  },
  {
    ageRating: "13+",
    badge: "Episode Baru",
    description:
      "Izuku Midoriya berlatih menjadi pahlawan profesional di dunia tempat kekuatan super menjadi hal umum.",
    episodes: [
      episode("Izuku Midoriya: Origin", "24 min", 1),
      episode("What It Takes to Be a Hero", "24 min", 2),
      episode("Roaring Muscles", "24 min", 3),
      episode("Start Line", "24 min", 4),
      episode("What I Can Do For Now", "24 min", 5),
    ],
    genreSlugs: ["anime", "aksi", "komedi"],
    image: imageUrl("ivOLM47yJt90P19RH1NvJrAJz9F.jpg"),
    isPremium: false,
    isTopTen: true,
    isTrending: true,
    previewImage: imageUrl("ivOLM47yJt90P19RH1NvJrAJz9F.jpg", "w780"),
    publishedAt: new Date("2026-02-10"),
    rating: 4.7,
    releaseYear: 2016,
    slug: "my-hero-academia",
    title: "My Hero Academia",
    trailerUrl: "https://www.youtube.com/embed/wIb3nnOeves",
    type: "SERIES",
  },
];

async function main() {
  for (const plan of packages) {
    const currentPackage = await prisma.package.findFirst({
      where: { name: plan.name },
    });

    if (currentPackage) {
      await prisma.package.update({
        data: plan,
        where: { id: currentPackage.id },
      });
    } else {
      await prisma.package.create({ data: plan });
    }
  }

  for (const [name, slug] of genres) {
    await prisma.genre.upsert({
      create: { name, slug },
      update: { name },
      where: { slug },
    });
  }

  for (const content of contents) {
    const { episodes, genreSlugs, ...contentData } = content;
    const savedContent = await prisma.seriesFilm.upsert({
      create: contentData,
      update: contentData,
      where: { slug: content.slug },
    });

    await prisma.seriesFilmGenre.deleteMany({
      where: { seriesFilmId: savedContent.id },
    });

    for (const genreSlug of genreSlugs) {
      await prisma.seriesFilmGenre.create({
        data: {
          genre: { connect: { slug: genreSlug } },
          seriesFilm: { connect: { id: savedContent.id } },
        },
      });
    }

    await prisma.episodeMovie.deleteMany({
      where: { seriesFilmId: savedContent.id },
    });

    await prisma.episodeMovie.createMany({
      data: episodes.map((item) => ({
        ...item,
        seriesFilmId: savedContent.id,
        thumbnailUrl: item.thumbnailUrl ?? content.previewImage,
        videoUrl: item.videoUrl ?? content.trailerUrl,
      })),
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
